### PR TITLE
RabbitMQ docs

### PR DESCRIPTION
**Pull request by lucperkins**
These docs are finished but we need to wait for resolution of #19 to merge.

### CODE REVIEW

**Comment by lucperkins** [comment]
@merlimat Can you un-merge this? RabbitMQ deployment is currently broken and I feel like it’d be best not to push these docs out until it’s fixed.

**Comment by merlimat** [comment]
Sure, let me revert it.

**Comment by merlimat** [comment]
@lucperkins But there are some fixes for the Ansible script already no? Any subsequent change should be based on this.

**Comment by lucperkins** [comment]
@merlimat That’s a good point. I’d say we can keep the changes for now, as it’s unlikely the RabbitMQ deployment configs will be used in the short term. The changes I made here were just cosmetic.

**Pull request merged**
